[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "I", # isort
    "N", # pep8-naming
    "D", # pydocstyle,
    "UP", # pyupgrade
    "ANN", # flake8-annotations
    "BLE", # flake8-blind-except
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "EM", # flake8-errmsg
    "FA", # flake8-future-annotations
    "ICN", # flake8-import-conventions
    "LOG", # flake8-logging
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PT", # flake8-pytest-style
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "FIX", # flake8-fixme
    "ERA", # eradicate
    "PD", # pandas-vet
    "FLY", # flynt
    "NPY", # NumPy-specific rules
    "RUF", #Ruff-specific rules
]
ignore = ["D100", "D101", "D102", "D103", "D104", "D107", "D417", "G004", "ERA001"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

